### ISSUE TITLE
Textes editor interface

### ISSUE THREAD

**Issue by everycook** [everycook/EveryCook#151]
Make an interface to search for textes and edit them in all languages. Make it acessible via damin interface. make thomas admin

**Comment by tbuerki** [comment]
How long would it take to implement something like this for our new page?
From time to time I come across errors in the texts and it would be easiest for me to just correct them instead of list all the individual spelling mistakes as issue here

**Comment by swerder** [comment]
this possibility is added in admin, please test and enjoy.
attention: it's only in testsystem, so to change productiv textes, this have to go to production first.

**Comment by tbuerki** [comment]
Excellent!
