### ISSUE TITLE
Flickr image import

### ISSUE THREAD

**Issue by everycook** [everycook/EveryCook#158]
What I want is that as soon as the User has left the english ingredient name field in the background we start looking for matching images and show him a selection of available pictures so je can just click on one of them to start the cropping tool. 
This can be done using the flickr API. Make a flickr account, and try to get images via AJAX into a test page corresponding to the string in the text box of this page.
Only search for images licensed cc-by-sa to avoid legal issues.
Retrieve the user name of the author of image, too. we need that.
if nothing comes back, because of a too long search string, search for substrings.
On your own account create a dummy image. Load this one and post a comment to your image (don't spam other accounts) that says "we used your image for our recipe database at http://everycook.org/db?thelinktothatrecipe we hope this is OK for you, Thank you very much for the nice picture"
Should also be possible via api. Of course it should be posted after we saved the cropped image, not before.

As soon as you have the image, load it into the cropper so we can crop and save it.

**Comment by tbuerki** [comment]
For the moment we're not using flickr

**Comment by everycook** [comment]
where do we get images from?

**Comment by tbuerki** [comment]
Users will upload them
