### ISSUE TITLE
Autocomplete loading failed

### ISSUE THREAD

**Issue by everycook** [everycook/EveryCook#162]
Check the autocomplete, it says loading failed

**Comment by everycook** [comment]
it works if you're logged in...

**Comment by everycook** [comment]
only in chrome, win7, IE works

**Comment by everycook** [comment]
firefox works, too

**Comment by everycook** [comment]
Can't reproduce it. really spooky bug...

**Comment by tbuerki** [comment]
couldn't find it either during testing. closing it until it shows up again
