### ISSUE TITLE
Ingredients details from select ingredients window

### ISSUE THREAD

**Issue by tbuerki** [everycook/EveryCook#168]
In the recipe creater in the ingredients search overlay, when a user clicks on "more details" and the overlay with the details appears, the user should be able to go back to the search overlay when the "ingredients details" overlay is closed

**Comment by swerder** [comment]
the user should go back to search always he close the detail overlay, or only by pressing a button to do so?

**Comment by tbuerki** [comment]
Whenever the user came to the detail overlay by clicking on an ingredient in the recipe creator ingredients search overlay, the user should always go back to search when closing the detail overlay.
