### ISSUE TITLE
Search field in top bar

### ISSUE THREAD

**Issue by tbuerki** [everycook/EveryCook#171]
At the top of the page on the left (next to the everycook logo) should be the recipe search bar (except on the main page). so that the user can search for a recipe wherever he is at the moment.

**Comment by swerder** [comment]
what should be the behavior of this search filed, after the search is submitted?
stay the value in field? is it cleared? ...
Show the search also on Recipe result page?
should the content of search field be changed if the user changes the search on the recipe result page?
what should happen if the user enter more text than there are space for?

**Comment by tbuerki** [comment]
After the search is submitted, the search field is emptied and instead the results page is shown with the content of the search being moved to the standard search field on the results page. Basically, the field has the same behavior as the search field on the start page. The field is not synced or updated based on entries in the search field on the results page.
When text is longer than the field, the text disappears from the view on the left side. Same as when entering long text into google search field.
