### ISSUE TITLE
Flags for cuisines

### ISSUE THREAD

**Issue by tbuerki** [everycook/EveryCook#172]
At some point we need to show a little flag next to the cuisine whenever we mention the type of cuisine (e.g. as filter or in the public profile). Once we start searching and downloading all the necessary flags, how should we store and name those flags, so that it is easiest for you to show them correctly on the website? Do we need a mapping table in our list of possible cuisines?

**Comment by swerder** [comment]
done. you can upload the images in admin area, as field of the cusine data.

**Comment by tbuerki** [comment]
There seems to be a bug in the cuisine data editing: when i go to admin > cuisine type > one of the cuisines (I tried Asian and European) and then click edit, the following error appears:

CException

Property "CusineTypes.CUT_IMG_AUTH" is not defined.

/var/www/db_wsd/lib/yii/framework/db/ar/CActiveRecord.php(145)

133      */
134     public function __get($name)
135     {
136         if(isset($this->_attributes[$name]))
137             return $this->_attributes[$name];
138         elseif(isset($this->getMetaData()->columns[$name]))
139             return null;
140         elseif(isset($this->_related[$name]))
141             return $this->_related[$name];
142         elseif(isset($this->getMetaData()->relations[$name]))
143             return $this->getRelated($name);
144         else
145             return parent::__get($name);
146     }
147 
148     /**
149      * PHP setter magic method.
150      * This method is overridden so that AR attributes can be accessed like properties.
151      * @param string $name property name
152      * @param mixed $value property value
153      */
154     public function __set($name,$value)
155     {
156         if($this->setAttribute($name,$value)===false)
157         {

Stack Trace
#0 	
+
 /var/www/db_wsd/lib/yii/framework/db/ar/CActiveRecord.php(145): CComponent->__get("CUT_IMG_AUTH")
#1 	
+
 /var/www/db_wsd/lib/yii/framework/web/helpers/CHtml.php(2529): CActiveRecord->__get("CUT_IMG_AUTH")
#2 	
+
 /var/www/db_wsd/lib/yii/framework/web/helpers/CHtml.php(2252): CHtml::resolveValue(CusineTypes, "CUT_IMG_AUTH")
#3 	
+
 /var/www/db_wsd/lib/yii/framework/web/helpers/CHtml.php(1434): CHtml::activeInputField("text", CusineTypes, "CUT_IMG_AUTH", array("size" => 30, "maxlength" => 30, "name" => "CusineTypes[CUT_IMG_AUTH]", "id" => "CusineTypes_CUT_IMG_AUTH"))
#4 	
+
 /var/www/db_wsd/lib/yii/framework/web/widgets/CActiveForm.php(725): CHtml::activeTextField(CusineTypes, "CUT_IMG_AUTH", array("size" => 30, "maxlength" => 30))
#5 	
–
 /var/www/db_wsd/protected/modules/admin/views/cusineTypes/_form.php(69): CActiveForm->textField(CusineTypes, "CUT_IMG_AUTH", array("size" => 30, "maxlength" => 30))

64             </div>
65         </div>
66     
67         <div class="row">
68             <?php echo $form->labelEx($model,'CUT_IMG_AUTH'); ?>
69             <?php echo $form->textField($model,'CUT_IMG_AUTH',array('size'=>30,'maxlength'=>30)); ?>
70             <?php echo $form->error($model,'CUT_IMG_AUTH'); ?>
71         </div>
72         <div class="row">
73             <?php echo $form->labelEx($model,'CUT_GPS_LAT'); ?>
74             <?php echo $form->textField($model,'CUT_GPS_LAT'); ?>

#6 	
+
 /var/www/db_wsd/lib/yii/framework/web/CBaseController.php(126): require("/var/www/db_wsd/protected/modules/admin/views/cusineTypes/_form....")
#7 	
+
 /var/www/db_wsd/lib/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal("/var/www/db_wsd/protected/modules/admin/views/cusineTypes/_form....", array("model" => CusineTypes), true)
#8 	
+
 /var/www/db_wsd/lib/yii/framework/web/CController.php(869): CBaseController->renderFile("/var/www/db_wsd/protected/modules/admin/views/cusineTypes/_form....", array("model" => CusineTypes), true)
#9 	
–
 /var/www/db_wsd/protected/modules/admin/views/cusineTypes/update.php(35): CController->renderPartial("_form", array("model" => CusineTypes))

30 ?>
31 
32 <h1><?php printf($this->trans->TITLE_CUSINETYPES_UPDATE, $model->CUT_ID); ?></h1>
33 <?php echo $this->renderPartial('_form', array(
34     'model'=>$model,
35     )); ?>

#10 	
+
 /var/www/db_wsd/lib/yii/framework/web/CBaseController.php(126): require("/var/www/db_wsd/protected/modules/admin/views/cusineTypes/update...")
#11 	
+
 /var/www/db_wsd/lib/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal("/var/www/db_wsd/protected/modules/admin/views/cusineTypes/update...", array("model" => CusineTypes), true)
#12 	
+
 /var/www/db_wsd/lib/yii/framework/web/CController.php(869): CBaseController->renderFile("/var/www/db_wsd/protected/modules/admin/views/cusineTypes/update...", array("model" => CusineTypes), true)
#13 	
–
 /var/www/db_wsd/protected/components/Controller.php(299): CController->renderPartial("update", array("model" => CusineTypes), true)

294         } else {
295             if ($ajaxLayout==null){
296                 $ajaxLayout = $this->layout.'_ajax';
297             }
298             if($this->beforeRender($view)) {
299                 $output=$this->renderPartial($view,$data,true);
300                 if(($layoutFile=$this->getLayoutFile($ajaxLayout))!==false)
301                         $output=$this->renderFile($layoutFile,array('content'=>$output),true);
302 
303                 $this->afterRender($view,$output);
304                 

#14 	
+
 /var/www/db_wsd/protected/components/Controller.php(320): Controller->renderAjax("update", array("model" => CusineTypes), null)
#15 	
+
 /var/www/db_wsd/protected/modules/admin/controllers/CusineTypesController.php(159): Controller->checkRenderAjax("update", array("model" => CusineTypes))
#16 	
+
 /var/www/db_wsd/protected/modules/admin/controllers/CusineTypesController.php(182): CusineTypesController->prepareCreateOrUpdate("2", "update")
#17 	
 unknown(0): CusineTypesController->actionUpdate("2")
#18 	
+
 /var/www/db_wsd/lib/yii/framework/web/actions/CAction.php(108): ReflectionMethod->invokeArgs(CusineTypesController, array("2"))
#19 	
+
 /var/www/db_wsd/lib/yii/framework/web/actions/CInlineAction.php(47): CAction->runWithParamsInternal(CusineTypesController, ReflectionMethod, array("id" => "2"))
#20 	
+
 /var/www/db_wsd/lib/yii/framework/web/CController.php(308): CInlineAction->runWithParams(array("id" => "2"))
#21 	
+
 /var/www/db_wsd/lib/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(CInlineAction)
#22 	
+
 /var/www/db_wsd/lib/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#23 	
+
 /var/www/db_wsd/lib/yii/framework/web/CController.php(1145): CFilter->filter(CFilterChain)
#24 	
+
 /var/www/db_wsd/lib/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(CFilterChain)
#25 	
+
 /var/www/db_wsd/lib/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(CFilterChain)
#26 	
+
 /var/www/db_wsd/lib/yii/framework/web/CController.php(291): CFilterChain->run()
#27 	
+
 /var/www/db_wsd/lib/yii/framework/web/CController.php(265): CController->runActionWithFilters(CInlineAction, array("accessControl"))
#28 	
+
 /var/www/db_wsd/lib/yii/framework/web/CWebApplication.php(282): CController->run("update")
#29 	
+
 /var/www/db_wsd/lib/yii/framework/web/CWebApplication.php(141): CWebApplication->runController("admin/cusineTypes/update/id/2")
#30 	
+
 /var/www/db_wsd/lib/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#31 	
+
 /var/www/db_wsd/index.php(13): CApplication->run()

**Comment by swerder** [comment]
fixed

**Comment by tbuerki** [comment]
Editing error is fixed. Now I tried to edit the cuisine (Australian) and when i changed the name and pressed save, the following indication appears:

Please fix the following input errors:

    ???FIELD_CUT_IMG_FILENAME??? cannot be blank.
    ???FIELD_CUT_IMG_ETAG??? cannot be blank.

**Comment by swerder** [comment]
fixed.
