### ISSUE TITLE
Suggested steps to add with ingredients

### ISSUE THREAD

**Issue by tbuerki** [everycook/EveryCook#177]
In the recipe creator, when adding an ingredient by selecting onion yellow, the window with the suggested steps appears and it shows steps that sometimes do not include the actual ingredient. My window for the onion yellow showed the following steps:

Add step
Please click on a step, to add the ingredient to recipe.
Prepare about 50g of onion yellow
Prepare about 10g of olive oil
Add olive oil as wished
cut onion yellow into fine stripes and put in Cooking pot
cut onion yellow into fine slices and put in Cooking pot
heatup to 120°C
cook 00:00:15h at 120°C

**Comment by swerder** [comment]
that is not a bug, its a feature! (as I say you in recipeCreator finished Mail)
it is a (currently fix defined) example, what would be possible.
because you will often roast the onion in oil, this steps are suggested to you...

**Comment by tbuerki** [comment]
True, sorry, I had forgotten that :)
