### ISSUE TITLE
Recipe results page broken?

### ISSUE THREAD

**Issue by tbuerki** [everycook/EveryCook#178]
The recipe results page is not showing anymore for me. My internet connection is not the best at the moment but the other pages seem to work fine (loading a bit slow though). After I start a search from the home page or the search field in the nav bar, I get an empty page that only shows the background picture plus the navigation bar on top and the copyright with cc straight under this nav bar. There's nothing else on the page. URL seems to be correct, e.g. it happens for http://www.everycook.org/db_wsd/#recipes/search?newSearch=1424300579&query=risotto
(using firefox and windows 8)

**Comment by swerder** [comment]
fixed, it was a debug output that I forgot do remove.
