### ISSUE TITLE
Meal planning bug

### ISSUE THREAD

**Issue by everycook** [everycook/EveryCook#179]
When I klick "create meal" in the meal planner I get a:
Fehler 404

Unable to resolve the request "#meals/mealList/170".

URL is:
http://everycook.org/db/%23meals/mealList/170?rec_id=4&_=1424853228585

**Comment by swerder** [comment]
fixed.
The problem was (only) in chrome, firefox don't have it.
The problem was only if you have just logged in (url not ajax style).
