### ISSUE TITLE
Recipe list api

### ISSUE THREAD

**Issue by everycook** [everycook/EveryCook#186]
We should be able to list recipes using the following keywords:
* lang
* rec_type
* rec_cuisine
* start (where to start the list of results useful for a second result page)
* end (end of the list, if page is limited)
* sort=az,za,new (and other sorting options later if needed)

and get a json output containing:
* lang
* title
* img_url
* rec_id
* and probably some other values I don't think of right now.

We want to include in every api call:
* token (the token to allow access, as long as we have no ssl, "everycook" is the only accepted token

We allow only read access by now, to void conflicts. later we want write access to some parts and have to ckeck if the token is safe enough for this if we have ssl active

**Comment by tbuerki** [comment]
Merged into #185

**Comment by everycook** [comment]
It would be great to have a parameter "lastchange" so we can check if a cached recipe is still up to date or if we have to re-sync it.

**Comment by swerder** [comment]
this issue is merged with 185, so please do not reopen it.
I copied lastchange to there.
