### ISSUE TITLE
Login Bug

### ISSUE THREAD

**Issue by everycook** [everycook/EveryCook#188]
Can't login to db_wsd. 
Undefined variable: allLanguages

/var/www/db_wsd/protected/components/Controller.php(90)

078     public function getIsAjaxRequest(){
079         $params = $this->getActionParams();
080         if (isset($params['noajax']) && $params['noajax']){
081             return false;
082         }
083         return $this->isFancyAjaxRequest || Yii::app()->request->isAjaxRequest || (isset($params['ajaxform']) && $params['ajaxform']);
084     }
085     
086     //protected $allLanguages = array('EN_GB'=>'English','DE_CH'=>'Deutsch','FR_FR'=>'Francais');
087     public static $allLanguages = array('EN_GB'=>'English','DE_CH'=>'Deutsch');
088     
089     public function getAllLanguages(){
090         return $allLanguages;
091     }
092     
093     public function getJumpTos(){
094         return array(
095             $this->trans->JUMPTO_SHOP_CREATOR => array(Yii::app()->createUrl('/stores/create',array('newModel'=>time())), ' newModelTime'),
096             $this->trans->JUMPTO_SHOP_FINDER => array(Yii::app()->createUrl('/stores/storeFinder',array())),
097             $this->trans->JUMPTO_LIKE_INGREDIENT => array(Yii::app()->createUrl('/ingredients/showLike',array())),
098             $this->trans->JUMPTO_LIKE_PRODUCTS => array(Yii::app()->createUrl('/products/showLike',array())),
099             $this->trans->JUMPTO_LIKE_RECIPES => array(Yii::app()->createUrl('/recipes/showLike',array())),
100             $this->trans->JUMPTO_MEALLIST => array(Yii::app()->createUrl('/meals/mealList',array())),
101 //            $this->trans->JUMPTO_MEALPLANNER => array(Yii::app()->createUrl('/meals/mealPlanner',array('newModel'=>time())), ' newModelTime'),
102             $this->trans->JUMPTO_SHOPPINGLISTS => array(Yii::app()->createUrl('/shoppinglists/index',array())),

**Comment by swerder** [comment]
fixed.
