### ISSUE TITLE
Recipe image upload button not working

### ISSUE THREAD

**Issue by everycook** [everycook/EveryCook#189]
Just wanted to set a pic for the roasted onions. nothing happens when I cklick on "choose file"

**Comment by swerder** [comment]
fixed.

**Comment by tbuerki** [comment]
Works for me now.

One other point on the image upload: Can we set the minimum size to 200x200 instead of 400 x 400pixels? 200 seems enough for the use cases we have and it gives us a larger selection of possible images.

**Comment by swerder** [comment]
As you say elsewhere the users have to upload there OWN images, and which camera make smaller images then 400x400?
Also all images are saved as 400x400 images on disk / selection will be resized.
Also I think 200 could be enough, but if you want also support Retina Displays, as they are on iPhones you need 400x400 to "show" 200x200 sized image.

**Comment by everycook** [comment]
Display resolutions only go up. so i think even 400x400 is limiting.... 200x200 will definitely look bad on a full HD or retina display

**Comment by tbuerki** [comment]
Ok, let's leave it for the moment and see if the test users bring it up later.
