### ISSUE TITLE
Improper display of Pro profiles

### ISSUE THREAD

**Issue by tbuerki** [everycook/EveryCook#194]
When the user clicks on the photo of the chef on a Pro recipe (in the search results page), the overlay doesn't properly display the profile page (it's too small and the elements are overlapping, see attached screens)

![profile_bug1](https://cloud.githubusercontent.com/assets/7896359/6881281/aa83ddf8-d558-11e4-930c-8672c29d9ef3.PNG)

![profile_bug2](https://cloud.githubusercontent.com/assets/7896359/6881293/1ad9be92-d559-11e4-8a91-18cc811da821.PNG)

**Comment by swerder** [comment]
how should it be?
a defined fix width so all has enough space?
or/and should I remove the  Recipes By Part in this overlay view?

**Comment by tbuerki** [comment]
Let's remove the "Recipes by" part for the overlay view and make it a fixed width so that the rest has enough space.

**Comment by swerder** [comment]
fixed.
