### ISSUE TITLE
Delete ingredients in the shopping list

### ISSUE THREAD

**Issue by tbuerki** [everycook/EveryCook#196]
On the shopping list page, each ingredient should have on the corner right of the white box a small "x" with which the ingredient can be deleted from the list.

**Comment by swerder** [comment]
Done.
Same as on change "haveIt" or adding recipe; the "remove" change is only persistent if the "save" button on bottom of list is pressed.
Without pressing save button, the change will stay on Press F5, but will disappear on changing to other shoppinglist.
