### ISSUE TITLE
Showing cusine type in recipe view

### ISSUE THREAD

**Issue by tbuerki** [everycook/EveryCook#199]
In the recipe view, the cuisine sub sub type is currently not shown. To make it easier for the user, there should only be one line that says "Cuisine type" and it shows [cuisine type], [sub cuisine type], [sub sub cuisine type] all next to each other. That way, it doesn't matter if there's only the first level of the cuisine type defined or two of them or all three.

**Comment by swerder** [comment]
fixed.

**Comment by tbuerki** [comment]
Does not yet work for me. In the recipe view I see the following:
![cusine_type1](https://cloud.githubusercontent.com/assets/7896359/6903419/84b8276e-d71a-11e4-83bc-a1593857e3e6.PNG)


The line for "cuisine type" should be shown identical as the view on the results page where type, sub type and sub sub type are all next to each other, like this:
![cusine_type2](https://cloud.githubusercontent.com/assets/7896359/6903451/a71d0478-d71a-11e4-8329-ea0a16523d4d.PNG)

**Comment by swerder** [comment]
I only done it on search result before, now on detail also done.
