### ISSUE TITLE
Image of ingredients does not show properly in search field on start page

### ISSUE THREAD

**Issue by tbuerki** [everycook/EveryCook#201]
When searching by ingredient on the start page ("what do you have in the fridge?" field), the image of the ingredients that are put into the search field are above the ingredient instead of on the side, distorting the picture completely.

![search_image_bug](https://cloud.githubusercontent.com/assets/7896359/6883771/e3762874-d5c5-11e4-98cd-c6e43b8670da.PNG)

**Comment by swerder** [comment]
fixed.
